### ISSUE TITLE
No publishable resources for tag [config].

### ISSUE THREAD

**Issue by indygill** [maltekuhr/laravel-gpt#5]
Laravel 9

When running the following artisan command

```
php artisan vendor:publish --provider="MalteKuhr\LaravelGPT\Providers\GPTServiceProvider" --tag="config"
```

the following warning is returned

```
INFO  No publishable resources for tag [config].
```

Running the same command without the --tag="config" parameter publishes the config file successfully.

**Comment by maltekuhr** [comment]
Hi @indygill,

thank you for your support. The tag in the documentation is `config` and in the code `public` which leads to no config file being publish. I will create a new release with the fix in the next hours.

Thank you for report!

#6
