### ISSUE TITLE
Sending files to GPT

### ISSUE THREAD

**Issue by Human018** [maltekuhr/laravel-gpt#9]
From what I can see in the source code - src/GPTAction.php there isn't an option to include a file attachment to the instructions being sent. Is this ability coming soon?

**Comment by maltekuhr** [comment]
Hello @Human018,

Currently, the GPT-4 Version preview does not offer support for function calls. However, I'm exploring the possibility of integrating support for other models like Claude 3 or Gemini, both of which already facilitate this feature.

![Screenshot](https://github.com/maltekuhr/laravel-gpt/assets/80050109/071b8256-a88d-43a6-b8e7-7f31515faf76)  
[OpenAI Documentation](https://platform.openai.com/docs/guides/vision)

Would the inclusion of such models interest you? Additionally, could you share how you plan to utilize the vision actions? Your feedback is invaluable and will greatly assist in tailoring the development of the next version to better meet user needs.

Looking forward to your thoughts!

**Comment by jhg** [comment]
> However, I'm exploring the possibility of integrating support for other models like Claude 3 or Gemini

That could be the easier change, and could be interesting to have other providers or self-hosted models, PR https://github.com/maltekuhr/laravel-gpt/pull/14 implements it and I test it doesn't break current usage.
